a = int (input("1 number : "))
b =  int (input("2 number : "))
print ("The value of ", a ,"+", b ,"=", a+b)
print ("The value of ", a ,"-", b ,"=", a-b)
print ("The value of ", a ,"*", b ,"=", a*b)
print ("The value of ", a ,"/", b ,"=", a/b)
print ("The value of ", a ,"//", b ,"=", a//b)